# Generated by Django 6.0.3 on 2026-03-16 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAlteracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.CharField(max_length=60)),
                ('registro_id', models.IntegerField()),
                ('operacao', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=6)),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('dados_antes', models.JSONField(blank=True, null=True)),
                ('dados_depois', models.JSONField(blank=True, null=True)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historico_alteracoes',
                'ordering': ['-alterado_em'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('papel_atividade', models.CharField(blank=True, max_length=100, null=True)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_categoria', models.CharField(choices=[('CUSTEIO', 'Custeio'), ('CAPITAL', 'Capital')], max_length=10)),
                ('nome_subcategoria', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'unique_together': {('tipo_categoria', 'nome_subcategoria')},
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ORÇADO', 'Orçado'), ('REALIZADO', 'Realizado')], max_length=10)),
                ('descricao_item', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_lancamento', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
            ],
            options={
                'db_table': 'lancamentos',
            },
        ),
        migrations.CreateModel(
            name='DetalhesTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meio_transporte', models.CharField(choices=[('Voo', 'Voo'), ('Ônibus', 'Ônibus'), ('Aplicativo', 'Aplicativo'), ('Táxi', 'Táxi'), ('Carro próprio', 'Carro próprio'), ('Aluguel de carro', 'Aluguel de carro')], max_length=20)),
                ('local_origem', models.CharField(blank=True, max_length=150, null=True)),
                ('local_destino', models.CharField(blank=True, max_length=150, null=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('data_chegada', models.DateField(blank=True, null=True)),
                ('horario_saida', models.TimeField(blank=True, null=True)),
                ('horario_chegada', models.TimeField(blank=True, null=True)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('custo_passagem', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_abastecimento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_aplicativo_taxi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_alimentacao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('lancamento', models.OneToOneField(db_column='lancamento_id', on_delete=django.db.models.deletion.CASCADE, to='core.lancamento')),
            ],
            options={
                'db_table': 'detalhes_transporte',
            },
        ),
        migrations.CreateModel(
            name='DetalhesServTerceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('Divulgação', 'Divulgação'), ('Revisão de texto', 'Revisão de texto'), ('Gráfica / impressão', 'Gráfica / impressão'), ('Tradução', 'Tradução'), ('Consultoria', 'Consultoria'), ('Desenvolvimento de software', 'Desenvolvimento de software'), ('Outros', 'Outros')], max_length=30)),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2)),
                ('nome_prestador', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('descricao_servico', models.CharField(max_length=500)),
                ('numero_contrato', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_nf_rpa', models.CharField(blank=True, max_length=20, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentual_retencao', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_retencao', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('lancamento', models.OneToOneField(db_column='lancamento_id', on_delete=django.db.models.deletion.CASCADE, to='core.lancamento')),
            ],
            options={
                'db_table': 'detalhes_servicos_terceiros',
            },
        ),
        migrations.CreateModel(
            name='DetalhesMatConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_material', models.CharField(choices=[('Papelaria', 'Papelaria'), ('Informática', 'Informática'), ('Material de escritório', 'Material de escritório'), ('Material de laboratório', 'Material de laboratório'), ('Outros', 'Outros')], max_length=30)),
                ('descricao_item', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('unidade_medida', models.CharField(default='un', max_length=20)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fornecedor', models.CharField(blank=True, max_length=150, null=True)),
                ('cnpj_fornecedor', models.CharField(blank=True, max_length=18, null=True)),
                ('numero_nf', models.CharField(blank=True, max_length=20, null=True)),
                ('data_compra', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('lancamento', models.ForeignKey(db_column='lancamento_id', on_delete=django.db.models.deletion.CASCADE, to='core.lancamento')),
            ],
            options={
                'db_table': 'detalhes_material_consumo',
            },
        ),
        migrations.CreateModel(
            name='DetalhesDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_diarias', models.IntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cidade_destino', models.CharField(blank=True, max_length=150, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('lancamento', models.OneToOneField(db_column='lancamento_id', on_delete=django.db.models.deletion.CASCADE, to='core.lancamento')),
            ],
            options={
                'db_table': 'detalhes_diaria',
            },
        ),
    ]
