# Generated by Django 6.0.3 on 2026-03-16 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalhesMaterialPermanente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_bem', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_patrimonio', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_nf', models.CharField(blank=True, max_length=20, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=150, null=True)),
                ('cnpj_fornecedor', models.CharField(blank=True, max_length=18, null=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('garantia_meses', models.IntegerField(default=12)),
                ('data_fim_garantia', models.DateField(blank=True, editable=False, null=True)),
                ('estado_conservacao', models.CharField(choices=[('Novo', 'Novo'), ('Bom', 'Bom'), ('Regular', 'Regular'), ('Necessita manutenção', 'Necessita manutenção'), ('Inativo', 'Inativo')], default='Novo', max_length=25)),
                ('localizacao', models.CharField(blank=True, max_length=150, null=True)),
                ('responsavel_bem', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('lancamento', models.OneToOneField(db_column='lancamento_id', on_delete=django.db.models.deletion.CASCADE, to='core.lancamento')),
            ],
            options={
                'db_table': 'detalhes_material_permanente',
            },
        ),
    ]
