# Generated by Django 6.0.3 on 2026-03-17 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_detalhesmaterialpermanente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('orgao_financiador', models.CharField(max_length=100)),
                ('numero_edital', models.CharField(blank=True, max_length=50, null=True)),
                ('ano', models.PositiveSmallIntegerField()),
                ('valor_total_aprovado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Encerrado', 'Encerrado'), ('Suspenso', 'Suspenso')], default='Em andamento', max_length=15)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projetos',
                'unique_together': {('orgao_financiador', 'numero_edital', 'ano')},
            },
        ),
        migrations.AddField(
            model_name='lancamento',
            name='projeto',
            field=models.ForeignKey(db_column='projeto_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='core.projeto'),
            preserve_default=False,
        ),
    ]
